runtime: python312
entrypoint: uvicorn fireside.main:app --host 0.0.0.0 --port $PORT

handlers:
# Serve static files from the 'static' directory
- url: /static
  static_dir: static

# Route all other requests to the FastAPI app
- url: /.*
  script: auto

# Instance class (controls performance/cost)
# F1 is the smallest
instance_class: F1

# Scaling
automatic_scaling:
  min_instances: 0
  max_instances: 1

# Environment variables available to the application instances.
# Standard environment variables for Google Cloud services and genai SDK Vertex AI config.
env_variables:
  # Replace with your actual Google Cloud Project ID
  GOOGLE_CLOUD_PROJECT: "your-gcp-project-id"

  # Replace with the region for your Vertex AI resources (e.g., us-central1)
  GOOGLE_CLOUD_LOCATION: "us-central1"

  # Explicitly tell the google-generativeai SDK to use Vertex AI backend and ADC
  GOOGLE_GENAI_USE_VERTEXAI: "True" # Use string "True" for env vars

  # Optional: Override the default model used in vertex_ai.py
  # Ensure this model is available in your project/location.
  # VERTEX_MODEL_ID: "gemini-1.5-pro-latest" # Keep this if you want to override the default in code
