runtime: python312
entrypoint: uvicorn fireside.main:app --host 0.0.0.0 --port $PORT

handlers:
# Serve static files from the 'static' directory
- url: /static
  static_dir: static

# Route all other requests to the FastAPI app
- url: /.*
  script: auto

# Instance class (controls performance/cost)
# F1 is the smallest
instance_class: F1

# Basic scaling
basic_scaling:
  max_instances: 1
  idle_timeout: 60m

